import type { Meta, StoryObj } from "@storybook/svelte-vite";
import DesktopShell from "./DesktopShell.svelte";
import type { AppRoute } from "../../lib/navigation.svelte";

const meta = { title: "Desktop 2/Screens", component: DesktopShell, parameters: { layout: "fullscreen" } } satisfies Meta<typeof DesktopShell>;
export default meta;
type Story = StoryObj<typeof meta>;
const screen = (routeOverride: AppRoute, viewport: string): Story => ({ args: { routeOverride }, parameters: { viewport: { defaultViewport: viewport } } });

export const Operations1600 = screen("operations", "desktop1600");
export const Operations1280 = screen("operations", "desktop1280");
export const Operations960 = screen("operations", "compact960");
export const Workspaces1600 = screen("workspaces", "desktop1600");
export const Workspaces1280 = screen("workspaces", "desktop1280");
export const Workspaces960 = screen("workspaces", "compact960");
export const Runs1600 = screen("runs", "desktop1600");
export const Runs1280 = screen("runs", "desktop1280");
export const Runs960 = screen("runs", "compact960");
export const Flow1600 = screen("flow", "desktop1600");
export const Flow1280 = screen("flow", "desktop1280");
export const Flow960 = screen("flow", "compact960");
export const Approvals1600 = screen("approvals", "desktop1600");
export const Approvals1280 = screen("approvals", "desktop1280");
export const Approvals960 = screen("approvals", "compact960");
export const Integrations1600 = screen("integrations", "desktop1600");
export const Integrations1280 = screen("integrations", "desktop1280");
export const Integrations960 = screen("integrations", "compact960");
export const Settings1600 = screen("settings", "desktop1600");
export const Settings1280 = screen("settings", "desktop1280");
export const Settings960 = screen("settings", "compact960");
export const TopologyFocus1600 = screen("topology-focus", "desktop1600");
export const TopologyFocus1280 = screen("topology-focus", "desktop1280");
export const TopologyFocus960 = screen("topology-focus", "compact960");
export const RunReview1600 = screen("run-review", "desktop1600");
export const RunReview1280 = screen("run-review", "desktop1280");
export const RunReview960 = screen("run-review", "compact960");
export const OperationsLoading: Story = { args: { routeOverride: "operations", previewState: "loading" } };
export const OperationsEmpty: Story = { args: { routeOverride: "operations", previewState: "empty" } };
export const OperationsOffline: Story = { args: { routeOverride: "operations", previewState: "offline" } };
export const OperationsError: Story = { args: { routeOverride: "operations", previewState: "error" } };
export const WorkspacesEmpty: Story = { args: { routeOverride: "workspaces", previewState: "empty" } };
export const RunsEmpty: Story = { args: { routeOverride: "runs", previewState: "empty" } };
export const ApprovalsEmpty: Story = { args: { routeOverride: "approvals", previewState: "empty" } };
export const IntegrationsEmpty: Story = { args: { routeOverride: "integrations", previewState: "empty" } };

export const OperationsSidebarCollapsed: Story = { args: { routeOverride: "operations", collapsedOverride: true } };
export const WorkspacesSidebarCollapsed: Story = { args: { routeOverride: "workspaces", collapsedOverride: true } };
export const FlowSidebarCollapsed: Story = { args: { routeOverride: "flow", collapsedOverride: true } };
export const SettingsSidebarCollapsed: Story = { args: { routeOverride: "settings", collapsedOverride: true } };
