[package]
name = "pytxo-tui"
description = "Pytxo Hypervisor Shell TUI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
pytxo-core.workspace = true
pytxo-orchestrate = { workspace = true, features = ["sanitize"] }
pytxo-runner.workspace = true
pytxo-shell.workspace = true
ratatui.workspace = true
tokio.workspace = true
